Update check-alphine-release-version.yml

diff --git a/.github/workflows/check-alphine-release-version.yml b/.github/workflows/check-alphine-release-version.yml
--- a/.github/workflows/check-alphine-release-version.yml
+++ b/.github/workflows/check-alphine-release-version.yml
@@ -12,18 +12,29 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check current Alpine release
-        id: check_release
         run: |
           CURRENT_VERSION=${{ vars.alpine_container_image_version }}
           echo "Alpine Current: $CURRENT_VERSION"
           echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
 
+      - name: Get the latest stable Alpine release from Docker Hub
+        id: get_latest_release
+        run: |
+          set -e
+          LATEST_RELEASE=$(curl -s https://hub.docker.com/v2/repositories/library/alpine/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
+          if [ -z "$LATEST_RELEASE" ]; then
+            echo "Failed to fetch latest Alpine release."
+            exit 1
+          fi
+          echo "Alpine Latest Stable: $LATEST_RELEASE"
+          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
+        
 
       - name: echo 
         id: echo_response
         run: | 
-          echo yes: $CURRENT_VERSION
-
+          echo local: $CURRENT_VERSION
+          echo hub: $LATEST_RELEASE
           
 
       
